#!/bin/bash

action=$1
shift

[ "$action" = "usage"  ] && {
  echo "    lbs"
  echo "       list by severity"
  echo "    "
  echo ""
  exit
}
# COMMAND: list by severity
## b lbs --fields="1,3,4,7,8"
## sub-options: --fields  - a field list compatible with cut command
## sub-options: --sort  - a field number to sort on, default 3. e.g. --sort="2 -r"
##              --sort sorts on original field list, so as to continue sorting on SEVERITY
##+               even after the fields are reduced
##+ move lbs to addons TODO
    echo
    echo " ---   Listing of issues sorted by severity  --- "
    echo
    opt_fields=${opt_fields:-"1-7,$TSV_TITLE_COLUMN1"}
    if [ -z "$opt_fields" ]; then
        formatted_tsv_headers
    else
        formatted_tsv_headers | cut -d '|' -f$opt_fields
    fi
    if [ -z "$opt_sort" ]; then
        opt_sort=$TSV_SEVERITY_COLUMN1
    fi
    data=$( 
    filter_data "$@" \
        | sort -t$'\t' -k$opt_sort \
        | cut -d $'\t' -f$opt_fields  \
        | sed -e "s/${DELIM}\(....-..-..\) ..:../$DELIM\1/g;" \
            -e  "/${DELIM}CRI${DELIM}/s/.*/${PRI_A}&${DEFAULT}/" \
            -e  "/${DELIM}MOD${DELIM}/s/.*/${PRI_B}&${DEFAULT}/" \
            -e "s/$DELIM/$TSV_OUTPUT_DELIMITER/g"  \
        )
        echo -e "$data"

        [ $TSV_VERBOSE_FLAG -gt 1 ] && { echo; echo  "Listing is sorted on field 3. You may reduce fields by using the --fields option. e.g. --fields=\"1,2,3,5,8\""; 
        echo
        echo "To change sort order, use --sort=n"
        echo "--sort=\"2 -r\""
        echo "sort field numbers pertain to _original_ field numbers"
    
    }
