#!/bin/bash

action=$1
shift

[ "$action" = "usage" -o $# -lt 1 ] && {
  echo "    mdepri item# item# ..."
  echo "    de-prioritize multiple items"
  echo "        mdepri 101 102 103"
  echo ""
  exit
}
while true
do
    if [[ -z "$1" ]]; then
        break
    fi
    item=$1
    $TSV_PROGNAME  -d "$TSV_CFG_FILE" depri $item
    shift
done
;
